import { Callback } from '@zmonitor/types';
export declare function observeFirstScreenPaint(callback: Callback): void;
export declare function isSafari(): boolean;
export declare function getResource(): PerformanceResourceTiming[];
export declare function isCache(entry: PerformanceResourceTiming): boolean;
export declare function getFCP(callback: Callback): void;
export declare function getLCP(callback: Callback): void;
export declare function getFID(callback: Callback): void;
export declare function getCLS(callback: Callback): void;
export declare function getTTFB(callback: Callback): void;
export declare function getWebVitals(callback: Callback): void;
